services:
  backend:
    build: backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: npm run dev
    working_dir: /app
    depends_on:
      - backend
